name: Render and Deploy RMarkdown Website
'on': push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: run script
        run: |-
          Rscript -e "write.csv(head(mtcars),"hello.csv")"